### PR TITLE
moved from kube-lego to kube-cert-manager

### PR DESCRIPTION
**Pull request by rporres**
It handles properly multi SAN certificates

### CODE REVIEW

**Comment by dpordomingo** [comment]
@rporres Ping me when you're ready to merge
(I have no criteria to evaluate it, but lgtm)

**Comment by rporres** [comment]
@smeruelo Can you review this? Our dear maintainer is shy

**Review by smeruelo — APPROVED** [review]
LGTM. I assume we're going to apply it soon, right? Otherwise, certificates will expire in January and kube-lego won't renew them because the `tls-acme` annotation is missing.

**Comment by rporres** [comment]
@smeruelo Yes I will merge this when I have kube-cert-manager deployed, not before. Thx for the review.

@dpordomingo Let's not merge this until I have deployed what I need in staging and prod

**Pull request merged**
